#!/bin/csh

set i=1
echo $i
while ($i <= 10)

	echo $i
	set NAME=`echo HEAT$i`
	./Client1_AddHeatChannel.out localhost 31000 $NAME
	#sleep 1
	./Client1_DelChannel.out localhost 31000 $NAME
	
	@ i = $i + 1
end
	./Client1_Shutdown.out localhost 31000 
