#!/bin/csh

set i=1
echo $i
while ($i <= 10)

	echo $i
	set NAME=`echo HEAT$i`
	./Client1_AddHeatChannel.out localhost 31000 $NAME
	#sleep 1
	./Client1_DelChannel.out localhost 31000 $NAME
	
	@ i = $i + 1
end

set i=1
while ($i <= 10)

	echo $i
	set NAME=`echo Pressure$i`
	./Client1_AddKA_N_ATDT_YChannel.out localhost 31000 $NAME
	#sleep 1
	./Client1_DelChannel.out localhost 31000 $NAME
	
	@ i = $i + 1
end

	set NAME=`echo Pressure`
	./Client1_AddKA_N_ATDT_YChannel.out localhost 31000 $NAME


# 	./Client1_Shutdown.out localhost 31000 
