#!/bin/csh

set i=1
echo $i
while ($i <= 1000)

	echo $i
	set NAME=`echo HEAT$i`
	./Client1_AddHeatChannel.out localhost 32000 $NAME
	#sleep 1
	./Client1_DelChannel.out localhost 32000 $NAME
	
	@ i = $i + 1
end
